In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Название": ["Железо", "Медь", "Алюминий", "Золото", "Серебро", "Титан", "Никель", "Олово", "Свинец", "Платина"],
    "Плотность (г/см³)": [7.87, 8.96, 2.70, 19.32, 10.49, 4.51, 8.90, 7.31, 11.34, 21.45],
    "Температура плавления (°C)": [1538, 1085, 660, 1064, 961, 1668, 1455, 232, 327, 1768],
    "Применение": [
        "Строительство, машиностроение",
        "Электрика, электроника",
        "Авиация, строительство",
        "Ювелирное дело, электроника",
        "Ювелирное дело, зеркала",
        "Авиация, медицина",
        "Сплавы, аккумуляторы",
        "Припои, покрытия",
        "Аккумуляторы, защита от радиации",
        "Катализаторы, ювелирное дело"
    ],
    "Доступность": [True, True, True, False, True, True, True, True, True, False]
}

df = pd.DataFrame(data)

In [3]:
df

,Название,Плотность (г/см³),Температура плавления (°C),Применение,Доступность
0,Железо,7.87,1538,"Строительство, машиностроение",True
1,Медь,8.96,1085,"Электрика, электроника",True
2,Алюминий,2.70,660,"Авиация, строительство",True
3,Золото,19.32,1064,"Ювелирное дело, электроника",False
4,Серебро,10.49,961,"Ювелирное дело, зеркала",True
5,Титан,4.51,1668,"Авиация, медицина",True
6,Никель,8.90,1455,"Сплавы, аккумуляторы",True
7,Олово,7.31,232,"Припои, покрытия",True
8,Свинец,11.34,327,"Аккумуляторы, защита от радиации",True
9,Платина,21.45,1768,"Катализаторы, ювелирное дело",False

In [4]:
df.shape

(10, 5)

In [5]:
df.columns

Index(['Название', 'Плотность (г/см³)', 'Температура плавления (°C)',
       'Применение', 'Доступность'],
      dtype='object')

In [6]:
df.head(4)

,Название,Плотность (г/см³),Температура плавления (°C),Применение,Доступность
0,Железо,7.87,1538,"Строительство, машиностроение",True
1,Медь,8.96,1085,"Электрика, электроника",True
2,Алюминий,2.70,660,"Авиация, строительство",True
3,Золото,19.32,1064,"Ювелирное дело, электроника",False

In [8]:
filter_df = df[(df["Плотность (г/см³)"] >= 7.0) & (df["Плотность (г/см³)"] <= 11.0)]

In [9]:
filter_df

,Название,Плотность (г/см³),Температура плавления (°C),Применение,Доступность
0,Железо,7.87,1538,"Строительство, машиностроение",True
1,Медь,8.96,1085,"Электрика, электроника",True
4,Серебро,10.49,961,"Ювелирное дело, зеркала",True
6,Никель,8.90,1455,"Сплавы, аккумуляторы",True
7,Олово,7.31,232,"Припои, покрытия",True

In [10]:
filter_df = df[df["Доступность"] == True]

In [11]:
filter_df

,Название,Плотность (г/см³),Температура плавления (°C),Применение,Доступность
0,Железо,7.87,1538,"Строительство, машиностроение",True
1,Медь,8.96,1085,"Электрика, электроника",True
2,Алюминий,2.70,660,"Авиация, строительство",True
4,Серебро,10.49,961,"Ювелирное дело, зеркала",True
5,Титан,4.51,1668,"Авиация, медицина",True
6,Никель,8.90,1455,"Сплавы, аккумуляторы",True
7,Олово,7.31,232,"Припои, покрытия",True
8,Свинец,11.34,327,"Аккумуляторы, защита от радиации",True